version: '3'

services:
  nginx1:
    image: nginx:1.13
    ports:
      - 8081:80
    volumes:
      - ./src1:/usr/share/nginx/html
      - ./logdir/app1:/var/log/nginx

  nginx2:
    image: nginx:1.13
    ports:
      - 8082:80
    volumes:
      - ./src2:/usr/share/nginx/html
      - ./logdir/app2:/var/log/nginx

  nginx_LB:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./nginx_LB/nginx.conf:/etc/nginx/nginx.conf
      - ./logdir/LB:/var/log/nginx

